### ISSUE TITLE
Simple test on Python 3.6.9 failed

### ISSUE THREAD

**Issue by GC1102** [FlyHighest/gpuinfo#3]
Running the example in the package site:

from gpuinfo import GPUInfo

available_device=GPUInfo.check_empty()
percent,memory=GPUInfo.gpu_usage()
min_percent=percent.index(min([percent[i] for i in available_device]))
min_memory=memory.index(min([memory[i] for i in available_device]))

I get the error:

Traceback (most recent call last):
  File "/..../sparse_test.py", line 12, in <module>
    available_device=GPUInfo.check_empty()

  File "/...../lib/python3.6/site-packages/gpuinfo/GPUInfo.py", line 29, in check_empty
    pid_current,percent,memory,gpu_used=get_info()

  File "/...../lib/python3.6/site-packages/gpuinfo/GPUInfo.py", line 84, in get_info
    mem=int(arrs[5][:-3])

ValueError: invalid literal for int() with base 10: '--shared-fi'

**Comment by tyz1994** [comment]
Hi, gpuinfo runs 'nvidia-smi' and handles its output. Could you please provide me with your nvidia driver version and an example of nvidia-smi output? Here is mine:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:17:00.0 Off |                  N/A |
| 35%   43C    P8     2W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:18:00.0 Off |                  N/A |
| 35%   47C    P8    15W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:65:00.0 Off |                  N/A |
| 35%   46C    P8     2W / 250W |     27MiB / 11016MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:B4:00.0 Off |                  N/A |
| 35%   36C    P8     4W / 250W |      1MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    2      1614      G   /usr/lib/xorg/Xorg                             9MiB |
|    2      1741      G   /usr/bin/gnome-shell                          15MiB |
+-----------------------------------------------------------------------------+
```
